export const category = [
  "Automechanic",
  "Appliance Repairs",
  "Car Repairs",
  "Generator Repairs",
  "Electrical Repairs",
  "Plumbing Repairs",
  "Carpentry Repairs",
  "Painting Repairs",
  "Tiling Repairs",
  "Welding",
  "Catering",
  "Cleaning",
  "Gardening",
  "Hair Dressing",
];
